---
title: "climate change may be throwing coral sex out of sync"

author:
  - name: Susan Milius
    url: "https://www.sciencenews.org/article/climate-change-throwing-coral-sex-out-sync"
date: 09-13-2019
categories:
  - ocean health
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.

## Vocabulary 

| Words from the text | Synonym/explanation in English |
| ------------------- | ------------------------------ |
| throwing out of sync| unbalance                      |
|   underappreciated  | underestimated                 |
| swaths of coral     |     group of coral             |
| gaining             |  win                           |
| monitoring          |     survey                     |
|   tiny              |    little , thin               |
|  several            |    many                        |
|  spawning           |   appear                       |
|   elsewhere         |  in another place              |
|   cues              |  indications                   |
|   waxes and wane    |  increase and decrease         |
| sample              |   pattern                      |



## Analysis table 

|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  | Tom Shlesinger , a marine biologist at Tel Aviv University , Taryn Foster , a coral biologist at california academy of science of San Francisco ,  James Guest, coral biologist at the Newcastle university   |
| Published in?                | 13-09-2019                                                          |
| General topic?               |  climate                                                            |
| Procedure/what was examined? | they survey the reproduction of coral in the red sea , particulary during the night |
| Conclusions/discovery?       |  the temperature of the water impact the reporduction and affect the mounth of the synchronization , the rising of the temperature causes severely bleach and die to the coral      |
| Remaining questions?         | Does the overfishing impact the reproduction of coral ? |


sicence news
<https://www.sciencenews.org/article/malin-pinsky-sn-10-scientists-to-watch>
>

